# DOCKER ENV

export EUREKA_SERVICE_NAME="infra-eureka"
export EUREKA_SERVICE_IMAGE_NAME="eureka-service"
export EUREKA_SERVICE_IMAGE_VERSION="0.0.1"
export NETWORK_NAME="bridge-signature"

# DOCKER IMAGE UPDATE

if docker image inspect $EUREKA_SERVICE_IMAGE_NAME:$EUREKA_SERVICE_IMAGE_VERSION &> /dev/null; then
    docker image rm -f $EUREKA_SERVICE_IMAGE_NAME:$EUREKA_SERVICE_IMAGE_VERSION
fi

docker build -t $EUREKA_SERVICE_IMAGE_NAME:$EUREKA_SERVICE_IMAGE_VERSION .

# DOCKER SERVICE RUN

if [ "$(docker ps -aq -f name=$EUREKA_SERVICE_NAME)" ]; then
    docker rm -f $EUREKA_SERVICE_NAME
fi

docker run -d \
--network $NETWORK_NAME \
--name $EUREKA_SERVICE_NAME \
-p $EUREKA_SERVICE_PORT:$EUREKA_SERVICE_PORT \
$EUREKA_SERVICE_IMAGE_NAME:$EUREKA_SERVICE_IMAGE_VERSION